import { Activity, Building, Room, Teacher, TimeSlot, TimetableEntry } from '../../../shared/types';

export interface FETExportData {
  institutionName: string;
  teachers: Teacher[];
  rooms: Room[];
  buildings: Building[];
  activities: Activity[];
  timeSlots: TimeSlot[];
  entries?: TimetableEntry[];
}

export class FETExporter {
  public static exportToXml(data: FETExportData): string {
    const { institutionName, teachers, rooms, buildings, activities, timeSlots, entries } = data;

    // Distinct days
    const daysMap = new Map<number, string>();
    timeSlots.forEach(s => daysMap.set(s.dayOfWeek, s.dayName));
    const days = Array.from(daysMap.values());

    // Distinct hours
    const hoursSet = new Set<string>();
    timeSlots.forEach(s => hoursSet.add(`${s.startTime}-${s.endTime}`));
    const hours = Array.from(hoursSet);

    let xml = `<?xml version="1.0" encoding="UTF-8"?>\n`;
    xml += `<fet version="6.0.0">\n`;
    xml += `  <Institution_Name>${this.escapeXml(institutionName)}</Institution_Name>\n`;
    xml += `  <Comments>Generated by University Timetable Management System (FET Compatible)</Comments>\n`;

    // Days List
    xml += `  <Days_List>\n`;
    xml += `    <Number_of_Days>${days.length}</Number_of_Days>\n`;
    days.forEach(d => {
      xml += `    <Day><Name>${this.escapeXml(d)}</Name></Day>\n`;
    });
    xml += `  </Days_List>\n`;

    // Hours List
    xml += `  <Hours_List>\n`;
    xml += `    <Number_of_Hours>${hours.length}</Number_of_Hours>\n`;
    hours.forEach(h => {
      xml += `    <Hour><Name>${this.escapeXml(h)}</Name></Hour>\n`;
    });
    xml += `  </Hours_List>\n`;

    // Teachers List
    xml += `  <Teachers_List>\n`;
    teachers.forEach(t => {
      xml += `    <Teacher><Name>${this.escapeXml(t.name)}</Name></Teacher>\n`;
    });
    xml += `  </Teachers_List>\n`;

    // Buildings List
    xml += `  <Buildings_List>\n`;
    buildings.forEach(b => {
      xml += `    <Building><Name>${this.escapeXml(b.name)}</Name></Building>\n`;
    });
    xml += `  </Buildings_List>\n`;

    // Rooms List
    xml += `  <Rooms_List>\n`;
    rooms.forEach(r => {
      const bld = buildings.find(b => b.id === r.buildingId);
      xml += `    <Room>\n`;
      xml += `      <Name>${this.escapeXml(r.name)}</Name>\n`;
      if (bld) {
        xml += `      <Building>${this.escapeXml(bld.name)}</Building>\n`;
      }
      xml += `      <Capacity>${r.capacity}</Capacity>\n`;
      xml += `    </Room>\n`;
    });
    xml += `  </Rooms_List>\n`;

    // Activities List
    xml += `  <Activities_List>\n`;
    activities.forEach((act, idx) => {
      xml += `    <Activity>\n`;
      xml += `      <Id>${idx + 1}</Id>\n`;
      act.teacherIds.forEach(tId => {
        const teach = teachers.find(t => t.id === tId);
        if (teach) {
          xml += `      <Teacher>${this.escapeXml(teach.name)}</Teacher>\n`;
        }
      });
      xml += `      <Subject>${this.escapeXml(act.name)}</Subject>\n`;
      if (act.activityTag) {
        xml += `      <Activity_Tag>${this.escapeXml(act.activityTag)}</Activity_Tag>\n`;
      }
      act.sectionIds.forEach(s => {
        xml += `      <Students>${this.escapeXml(s)}</Students>\n`;
      });
      xml += `      <Duration>${act.durationPeriods}</Duration>\n`;
      xml += `      <Total_Students>${act.totalStudentCount}</Total_Students>\n`;
      xml += `    </Activity>\n`;
    });
    xml += `  </Activities_List>\n`;

    // Time Constraints & Space Constraints
    xml += `  <Time_Constraints_List>\n`;
    xml += `    <ConstraintBasicCompulsoryTime>\n`;
    xml += `      <Weight_Percentage>100</Weight_Percentage>\n`;
    xml += `    </ConstraintBasicCompulsoryTime>\n`;
    xml += `  </Time_Constraints_List>\n`;

    xml += `  <Space_Constraints_List>\n`;
    xml += `    <ConstraintBasicCompulsorySpace>\n`;
    xml += `      <Weight_Percentage>100</Weight_Percentage>\n`;
    xml += `    </ConstraintBasicCompulsorySpace>\n`;
    xml += `  </Space_Constraints_List>\n`;

    xml += `</fet>\n`;
    return xml;
  }

  private static escapeXml(unsafe: string): string {
    return unsafe
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&apos;');
  }
}
